r"""
Dictionary keys and column names.
"""

litdata_id = "id"
litdata_index = "index"
litdata_label = "label"
litdata_omics = "omics"
omics_dim = "omics_dim"
omics_feature = "omics_feature"
model_output_dim = "model_output_dim"

id = "ID"
label = "label"
ckpt_path = "path_ckpt"
which_outer = "x_outer"
which_inner = "x_inner"
val_loss = "val_loss"

gblock2gtype = "block2gtype"
gblock_ids = "block_ids"
sample_ids = "sample_ids"
snp_ids = "snp_ids"
genotype_matrix = "gt_mat"

lr = "learning_rate"
patience = "patience"
max_epochs = "max_epochs"
min_epochs = "min_epochs"
bsize = "batch_size"
s2g_dense_layer_dims = "dense_layers_hidden_dims"
hidden_dim = "hidden_dim"
num_heads = "n_heads"
num_encoders = "n_encoders"
dropout = "dropout"

best_trials = "logs"
best_inner_folds = "best_inners"

trial_tag = "trial_tag"
study_tag = "study_tag"
study_name = "study_name"
min_loss = "min_loss"
time_str = "x_time"

omics = "omics"
feature = "feature"
feat_importance = "importance"
